---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "tw-validating-webhook"
webhooks:
  - name: "validating-webhook.twistlock.com"
    # namespaceSelector
    # matchPolicy: Equivalent # v1.15+
    # timeoutSeconds: 2 # v1.14+
    admissionReviewVersions: ["v1", "v1beta1"] # Specify what versions of AdmissionReview objects are accepted
    sideEffects: None # sideEffects must be set to None or NoneOnDryRun
    failurePolicy: Ignore # Default failurePolicy is Fail
    rules:
      - operations: ["CREATE", "UPDATE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*/*"]
    clientConfig:
      # caBundle field should be similar to the CA bundle from the Defender DaemonSet YAML. Make sure to change it if you are using an older Defender CA.
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lSQUp2S0syemI1YXdpdWVzVHZ5dWw1VGd3RFFZSktvWklodmNOQVFFTEJRQXcKS0RFU01CQUdBMVVFQ2hNSlZIZHBjM1JzYjJOck1SSXdFQVlEVlFRREV3bFVkMmx6ZEd4dlkyc3dIaGNOTWpNdwpNakEyTWpFME1qQXdXaGNOTWpZd01qQTFNakUwTWpBd1dqQW9NUkl3RUFZRFZRUUtFd2xVZDJsemRHeHZZMnN4CkVqQVFCZ05WQkFNVENWUjNhWE4wYkc5amF6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFMdk01ektxaUJNT1cvVk1XUVFvYnNRNGlSQUFaalZiSEhNUmh4QmRvSmV6c2tkU0kycWVKZ2lQcmY2Uwp1dG5hWnZOWGJSY1ZHd2JSREkzc0JoMGFBWmxqK2Jtb2xrNTJ6bllicHRMNTBmcHNoUXBZdzBaUGlNR1Y5OFlICmVKUU0vekxFdm0vTHFhdlgrT0pVUWY1MWphUGtoakRFZDZ1SXVKSkM0K2lGMkxqUTJDYVVZK0hDNnhVRkx4OXIKZDdqclNHSDRXcCswcVlDak5SVHE2Um90UklVSDFMclcrd1k3TDRCcHdjTVltUTgxeGVHZ3d3cTJiRGNWMGl1bApZdVJ5YjdXSUR4TFZXTVhuR2xQTS9KTmc1QkZ4SHppcGs2ZFJwaTc0L3o4amRxMmV6Q1NJQkFQSFJwaVl4b1o1CkhOWUx2WEdXM2dDREwvRjc0ZEUvalR3WUZBMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLc01BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQXdRQTVBOUpSSzFDQm1IdFpLMjZQOWJieC9aTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnBQTEJEcUFMc2xCdFNscHY1MGJmTUY3VUFVV3lHaVVPOWFFaFdVYnJECjBDT3RhSGY3QnRvT1dlUVNkTkxQUHVtdDNMN1Q4MFY4d21TLzd2a3NlSXNQaThqcjh1aTYreFV0dlgwOUNKczAKOU0rczZUazdHVk1JVmQ0ZXRxMFRGenZBc0JaUGtERHN2WnpWVGRZSStxOHBMZlpaaE5VQlMxc1R6d01zdGxjdgo1ODVFdHlnTmZtTlhZR3A3dHB6TWZXbWZFRys1Q0dYb1pkalB4TkJnTXovbGVLaEdnWlB5UU8yWjRQcWhQTDNyCnV0Y0pUeXRGL09FOUlVdEZZTm5RamxQL0VpTDQwOEpkb0NyVnRGMllseEtLRHFrelo2L0EyR0ptS0o5Z2szWlgKYlNoMWttZ2pBSWRLVDduOE5lSFlQd3Zkb3hZZ2JNNmRoUTJ5ZGVSTld4Zm0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: defender
        namespace: "twistlock"
        path: "/p75qerhtq4ummccslzlq5psnpgfz"