trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
variables:
  - group: aws-demo-attack-lab-v2
  
stages:
    - stage: Infra_Deploy
      displayName: Despliegue de Infraestructura
      jobs:
        - job: IaC_Validation
          displayName:  Validacion de IaC
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: '$(backendServiceAWS)'
              backendAWSBucketName: '$(backendAWSBucketName)'
              backendAWSKey: '$(Build.Repository.Name)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: 'aws'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'aws'
              command: 'plan'
              environmentServiceNameAWS: '$(backendServiceAWS)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - job: Security_Gate
          displayName:  Escaneo de IaC (Security)
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
            displayName: 'Install Python 3.8'
          - script: pip install checkov
            displayName: 'Installing Prisma Cloud Code Security'
          - script: |
              export BC_SOURCE="azuredevops"
              echo $BC_SOURCE
              checkov --prisma-api-url $(CONSOLE) --bc-api-key $(PRISMA_TOKEN) -d . --repo-id $(System.TeamProject)/$(Build.Repository.Name) --branch $(Build.SourceBranchName) --use-enforcement-rules
            displayName: 'Scan Repo with Prisma Cloud'
