trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
variables:
  - group: aws-demo-attack-lab-v2
  
stages:
    - stage: IaC_Validation
      displayName: Validacion de IaC
      jobs:
        - job: terraform_init
          displayName:  Terraform Init
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: '$(backendServiceAWS)'
              backendAWSBucketName: '$(backendAWSBucketName)'
              backendAWSKey: '$(Build.Repository.Name)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - job: terraform_validate
          dependsOn: IaC_Validation
          displayName:  Terraform Validate
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: 'aws'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - job: terraform_plan
          dependsOn: terraform_validate
          displayName:  Terraform Plan
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'aws'
              command: 'plan'
              environmentServiceNameAWS: '$(backendServiceAWS)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    - stage: Security_Gate
      displayName: Escaneo de IaC (Security)
      jobs:
        - job: python_install
          displayName:  Instalacion Python
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
        - job: checkov_install
          displayName:  Instalacion Checkov
          steps:
          - script: pip install checkov
        - job: checkov_scan
          displayName:  Escaneo con Checkov
          steps:
          - script: |
              export BC_SOURCE="azuredevops"
              echo $BC_SOURCE
              checkov --prisma-api-url $(PRISMA_CONSOLE) --bc-api-key $(PRISMA_TOKEN) -d . --repo-id $(System.TeamProject)/$(Build.Repository.Name) --branch $(Build.SourceBranchName) --use-enforcement-rules
