trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
variables:
  - group: aws-demo-attack-lab-v2
  
stages:
    - stage: Infra_Deploy
      displayName: Infra Deploy
      jobs:
        - job: init
          displayName:  Terraform Init
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: '$(backendServiceAWS)'
              backendAWSBucketName: '$(backendAWSBucketName)'
              backendAWSKey: '$(Build.Repository.Name)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - job: validate
          displayName:  Terraform Validate
          steps:
            - task: TerraformTaskV4@4
              displayName: Terraform Validate
              inputs:
                provider: 'aws'
                command: 'validate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - job: plan
          displayName:  Terraform Plan
          steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'aws'
              command: 'plan'
              environmentServiceNameAWS: '$(backendServiceAWS)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra'